default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: rails_app_development

test:
  <<: *default
  database: rails_app_test

production:
  <<: *default
  database: postgre_sql_2f6o
  username: postgre_sql_2f6o_user
  password: sJfxvGLlA1v1LxKOn7TMn5G3bVg6aI1r
  host: dpg-crvdrdlds78s73elgurg-a.singapore-postgres.render.com
  port: 5432
